apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: mcp-system
  labels:
    app: mcp-conductor
    component: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-conductor
      component: mcp-server
  template:
    metadata:
      labels:
        app: mcp-conductor
        component: mcp-server
    spec:
      serviceAccountName: mcp-server
      containers:
      - name: mcp-server
        image: mcp-conductor:latest
        imagePullPolicy: Never  # For local development with Minikube
        command: ["/app/mcp-server"]
        args: ["--http", "--port", "8080"]
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_DEVELOPMENT
          value: "false"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 65534
      terminationGracePeriodSeconds: 30
