apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-system

resources:
- namespace.yaml
- service.yaml
- deployment.yaml

commonLabels:
  app: mcp-conductor
  version: v0.1.0

images:
- name: mcp-conductor
  newTag: latest
