apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: mcp-system
  labels:
    app: mcp-conductor
    component: mcp-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mcp-conductor
    component: mcp-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-server
  namespace: mcp-system
  labels:
    app: mcp-conductor
    component: mcp-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-server
  labels:
    app: mcp-conductor
    component: mcp-server
rules:
- apiGroups: ["mcp.io"]
  resources: ["tasks", "agents"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["mcp.io"]
  resources: ["tasks/status", "agents/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["pods", "nodes", "services"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-server
  labels:
    app: mcp-conductor
    component: mcp-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-server
subjects:
- kind: ServiceAccount
  name: mcp-server
  namespace: mcp-system
